name: Template Configuration
description: Configuration for this template repository
about: These values will be replaced in template files when creating a new repository. Please note that the npm_scope will be used, in the package name. It will look like @npm_scope/project_name

inputs:
  npm_scope:
    description: "NPM scope (without @)"
    required: true
    
  project_name:
    description: "Name of the project"
    required: true
    default: "my-typescript-lib"

  project_description:
    description: "Description of the project"
    required: false
